server:
  servlet:
    context-path: /fetch
  port: 9012
  http2:
    enabled: true

spring:
  application:
    name: foundation-fetch
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
    #date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
    time-zone: GMT+8

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# 消息主题配置
mq:
  topic:
    blockchain-transaction-topic: Blockchain_Transaction_Topic
