server:
  servlet:
    context-path: /flowline
  port: 9013
  http2:
    enabled: true

spring:
  application:
    name: foundation-flowline
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
    #date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: net.foundation.mbusiness.domain
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# 消息主题配置
mq:
  topic:
    blockchain-transaction-topic-1: Blockchain_Transaction_Topic_1
    blockchain-transaction-topic-2: Blockchain_Transaction_Topic_2
