server:
  servlet:
    context-path: /api
  port: 9011
  http2:
    enabled: true

spring:
  application:
    name: foundation-api
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
    #date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: true
    time-zone: GMT+8

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: net.foundation.mbusiness.domain
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

springfox:
  documentation:
    auto-startup: false
    enabled: false
